import { useMemo, useState } from 'react';
import { FileText, Send } from 'lucide-react';
import type { Resume } from '../types';
import { sendHospitalEmail } from '../api/email';

type Props = { resumes: Resume[]; selectedResume: Resume | null; onSelectResume: (resume: Resume | null) => void };

export function JobApplicationWorkspace({ resumes, selectedResume, onSelectResume }: Props) {
  const [firstName, setFirstName] = useState('');
  const [email, setEmail] = useState('');
  const [company, setCompany] = useState('');
  const [jobLink, setJobLink] = useState('');
  const [kind, setKind] = useState<'referral' | 'hr'>('referral');
  const [status, setStatus] = useState('');
  const data = useMemo(() => kind === 'referral'
    ? { label: 'Ask for a referral', subject: `Question about ${company || '{{company}}'}`, body: `Hi ${firstName || '{{first name}}'},\n\nI’m applying for a role at ${company || '{{company}}'} and wanted to reach out because I’ve been really interested in the work your team is doing. Here is the job posting: ${jobLink || '{{job link}}'}\n\nMy background is in building software and working on projects involving intelligent systems, machine learning, data, and applied product development. The work at ${company || '{{company}}'} seems closely aligned with the kinds of problems I enjoy working on.\n\nIf you have 15 minutes, I’d really appreciate the chance to hear about your experience and learn more about the team. If, after speaking, you feel my background could be a fit, I’d also be grateful if you would consider referring me. No worries at all if not.\n\nI attached my resume for context.\n\nThanks for your time,\nThuan` }
    : { label: 'Ask HR about the company', subject: `Interest in opportunities at ${company || '{{company}}'}`, body: `Hi ${firstName || '{{first name}}'},\n\nI’ve been following ${company || '{{company}}'} and really like the work you’re doing. I’m currently exploring software and applied technology opportunities, and I believe my background could be a strong fit for the kind of work your teams are doing.\n\nI’m especially interested in this opportunity: ${jobLink || '{{job link}}'}\n\nIf you have 15 minutes, I’d really appreciate the opportunity to learn more about ${company || '{{company}}'}, the team, and what you look for in candidates with my background.\n\nI attached my resume for context.\n\nThank you for your time,\nThuan` }, [kind, firstName, company, jobLink]);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!firstName || !email || !company || !jobLink) return setStatus('Fill in every field before sending.'); try { setStatus('Sending...'); await sendHospitalEmail({ to: email, subject: data.subject, body: data.body, resumeFilename: selectedResume?.name, senderWorkspace: 'thuan' }); setStatus('Email sent through your Gmail account.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Send failed.'); } }
  return <form onSubmit={submit} className="mx-auto max-w-4xl space-y-5">
    <div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-indigo-600">Job outreach</p><h2 className="mt-1 text-2xl font-semibold text-slate-950">Write a new email</h2><p className="mt-1 text-sm text-slate-500">Fill out the details, choose a resume, and send from your signed-in Gmail.</p></div>
    <section className="grid gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:grid-cols-2">{[['First name', firstName, setFirstName, 'text'], ['Email', email, setEmail, 'email'], ['Company', company, setCompany, 'text'], ['Job link', jobLink, setJobLink, 'url']].map(([label, value, setter, type]) => <label key={label as string} className="text-sm font-medium text-slate-700">{label as string}<input type={type as string} value={value as string} onChange={e => (setter as (value: string) => void)(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" placeholder={label === 'Job link' ? 'https://...' : ''} /></label>)}</section>
    <div className="flex gap-2"><button type="button" onClick={() => setKind('referral')} className={`rounded-lg px-3 py-2 text-sm font-medium ${kind === 'referral' ? 'bg-indigo-600 text-white' : 'bg-slate-100 text-slate-700'}`}>Ask for a referral</button><button type="button" onClick={() => setKind('hr')} className={`rounded-lg px-3 py-2 text-sm font-medium ${kind === 'hr' ? 'bg-indigo-600 text-white' : 'bg-slate-100 text-slate-700'}`}>Ask HR about the company</button></div>
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-semibold">{data.subject}</p><pre className="mt-4 whitespace-pre-wrap font-sans text-sm leading-6 text-slate-700">{data.body}</pre></section>
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2 text-sm font-semibold"><FileText className="h-4 w-4" /> Resume attachment</div><select value={selectedResume?.name || ''} onChange={e => onSelectResume(resumes.find(r => r.name === e.target.value) || null)} className="mt-3 w-full rounded-lg border border-slate-300 px-3 py-2"><option value="">Do not attach a resume</option>{resumes.map(r => <option key={r.name} value={r.name}>{r.originalName}</option>)}</select></section>
    {status && <p role="status" className="text-sm text-slate-700">{status}</p>}<button className="flex w-full items-center justify-center gap-2 rounded-lg bg-indigo-600 px-4 py-3 text-sm font-semibold text-white"><Send className="h-4 w-4" /> Send email</button>
  </form>;
}
